name: jify_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 0.21.0+1
  get: 4.3.0
  get_storage: 2.0.2
  pin_code_fields: 7.0.0
  dots_indicator: 2.0.0
  badges: 2.0.1
  modal_bottom_sheet: 2.0.0
  fluttertoast: 8.0.4
  dio: 4.0.0
  dartz: 0.10.0-nullsafety.2
  flutter_spinkit: 5.0.0
  cached_network_image: 3.1.0
  custom_check_box: 0.0.4
  flutter_countdown_timer: 4.1.0
  google_maps_flutter: 2.0.6
  firebase_messaging: ^10.0.4
  firebase_core: ^1.4.0
  connectivity: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 1.5.3


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: PulpDisplay
      fonts:
        - asset: assets/fonts/PulpDisplay-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/PulpDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/PulpDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/PulpDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/PulpDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PulpDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/PulpDisplay-ExtraBold.ttf
          weight: 900

    - family: PulpDisplayItalic
      fonts:
        - asset: assets/fonts/PulpDisplay-ExtraLightItalic.ttf
          weight: 200
        - asset: assets/fonts/PulpDisplay-LightItalic.ttf
          weight: 300
        - asset: assets/fonts/PulpDisplay-RegularItalic.ttf
          weight: 400
        - asset: assets/fonts/PulpDisplay-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/PulpDisplay-SemiBoldItalic.ttf
          weight: 600
        - asset: assets/fonts/PulpDisplay-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/PulpDisplay-ExtraBoldItalic.ttf
          weight: 900

